### ISSUE TITLE
Trying to install googleapis-common-protos fails

### ISSUE THREAD

**Issue by kootenpv** [googleapis/googleapis#406]
```
[pascal@archbook]: ~>$ pip3.7 install googleapis-common-protos
Collecting googleapis-common-protos
  Using cached googleapis-common-protos-1.5.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/pascal/python/lib/python3.7/site-packages/setuptools/__init__.py", line 10, in <module>
        from setuptools.extern.six.moves import filter, filterfalse, map
      File "/home/pascal/python/lib/python3.7/site-packages/setuptools/extern/__init__.py", line 1, in <module>
        from pkg_resources.extern import VendorImporter
      File "/home/pascal/python/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3017, in <module>
        @_call_aside
      File "/home/pascal/python/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3003, in _call_aside
        f(*args, **kwargs)
      File "/home/pascal/python/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3045, in _initialize_master_working_set
        dist.activate(replace=False)
      File "/home/pascal/python/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2577, in activate
        declare_namespace(pkg)
      File "/home/pascal/python/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2151, in declare_namespace
        _handle_ns(packageName, path_item)
      File "/home/pascal/python/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2091, in _handle_ns
        _rebuild_mod_path(path, packageName, module)
      File "/home/pascal/python/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2120, in _rebuild_mod_path
        orig_path.sort(key=position_in_sys_path)
    AttributeError: '_NamespacePath' object has no attribute 'sort'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-91us_qdk/googleapis-common-protos/
```

**Comment by kootenpv** [comment]
Actually, it works on python 3.6 but not on python 3.7 (git master).

**Comment by garribas** [comment]
Reproduced with python 3.6.

> $ python --version
> Python 3.6.0
> $ pip freeze --all | grep setuptools
> setuptools==28.8.0

Workaround:
> $ pip install --upgrade setuptools
> $ pip freeze --all | grep setuptools
> setuptools==36.5.0

And then `pip install googleapis-common-protos` works fine.

**Comment by namgivu** [comment]
My `virtualenv -p python3` only gives me python 3.5.2 in Ubuntu Desktop 16 - how can I get python 3.6?
